# Generated by Django 5.2 on 2025-05-08 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem_price_alter_profile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adress',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_cart'),
        ),
    ]
