# Generated by Django 5.2 on 2025-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_customer_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_adress',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_adress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
